DROP TABLE IF EXISTS goal CASCADE;
CREATE TABLE goal(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL, 
  task_id INTEGER REFERENCES task(id) ON DELETE CASCADE,
  goal_end DATE NOT NULL,
  completed BOOLEAN NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);