DROP TABLE IF EXISTS goal CASCADE
CREATE TABLE goal(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES user(id) ON DELETE,
  name VARCHAR(255) NOT NULL, 
  content TEXT, 
  goal_end DATE NOT NULL,
  completed BOOLEAN DEFAULT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);